//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CD67.ModeleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viking()
        {
            this.NombreVictoires = 0;
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public bool CasqueCornu { get; set; }
        public Nullable<int> NombreVictoires { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateEdition { get; set; }
        public int TypeVikingId { get; set; }
    
        public virtual TypeViking TypeViking { get; set; }
    }
}
